#!/bin/bash

output=${1:-"expat_tests.log"} # default log file

# logging function
function testCheck() {
	testExec="$1"
	shift
	echo && echo ${testExec} && ./${testExec} "$@"
	error=$?
	result=$([[ ${error} -eq 0 ]] && echo "PASS" || echo "FAIL")
	echo "${result}: ${testExec}" && echo "============================"
}

export output
export -f testCheck
TIME=$(which time)

echo "runtests"
${TIME} -f 'Execution time: %e s' bash -c "./runtests -v"
echo "runtestspp"
${TIME} -f 'Execution time: %e s' bash -c "./runtestspp -v"
echo
